version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/node/app/src
    container_name: "${WEBSEVERNAME}"
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    command: npm run start
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
  nginx:
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./nginx
volumes:
  data-volume:
